services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: worldsys-sqlserver
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./scripts/database-setup.sql:/tmp/database-setup.sql:ro
    networks:
      - worldsys-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Node.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worldsys-nodejs-app
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=0.0.0.0
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USERNAME=sa
      - DB_PASSWORD=YourStrong@Passw0rd
      - DB_NAME=master
    ports:
      - "3001:3001"
    depends_on:
      - sqlserver
    networks:
      - worldsys-network
    volumes:
      - ./clients:/app/clients:ro
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  worldsys-network:
    driver: bridge 